# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c453eea8d3711a44c83ab3e5ba2a9cf4f6a92446ba24ef00cb35ead14abc4a855edec7a2afb795165da221955daab217f99cd8bf19bb71b790f394aa6fad9773

test:
  secret_key_base: 85779f80744e5c23eb09ec1c0b60e76950d540bcc444a32eeb49b9355d40ed2d90f372baa05ee9304280ad141f952df98f3747fc13583779ca8ecda64de3a459

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
